name: Seckill HUD MAX Cloud Build

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Extract Zip Source
      run: |
        mkdir -p project_src
        unzip -q -o *.zip -d project_src/
    - uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'zulu'
    - uses: nttld/setup-ndk@v1
      with:
        ndk-version: r25c
    - name: Compile APK
      run: |
        GRADLE_DIR=$(dirname $(find project_src -name gradlew | head -n 1))
        cd "$GRADLE_DIR"
        chmod +x gradlew
        ./gradlew assembleDebug --stacktrace
    - uses: actions/upload-artifact@v4
      with:
        name: Seckill-HUD-MAX-Release
        path: project_src/**/app/build/outputs/apk/debug/*.apk
